### ISSUE TITLE
Positional arguments error

### ISSUE THREAD

**Issue by moltzaum** [ryanv3160/cyber-final-project#4]
When I run the detector code on the latest revision of the master branch I get the following output:
```
# ./main.py 
ARP Spoofer detector initialized
press [Ctrl+C] to quit
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: detect() missing 2 required positional arguments: 'rate_time_threshold' and 'rate_ips'
```

**Comment by moltzaum** [comment]
Resolved
